# Creating and  Using  Arrays in Python 

In [1]:
import numpy as np
list1=[1,2,3,4]

array1=np.array(list1)

Converting list1 of integers to numpy array array1

In [2]:
array1

array([1, 2, 3, 4])

Print out array1

In [7]:
list2=[11,22,33,44]

Create a new list of integers

In [8]:
mylist=[list1,list2]

create a new List contains the two lists list1+list2

In [9]:
array=np.array(mylist)

create two dimensional array containes two lists

In [10]:
array

array([[ 1,  2,  3,  4],
       [11, 22, 33, 44]])

print out the array

In [11]:
list1

[1, 2, 3, 4]

In [12]:
array.shape

(2, 4)

Get size of the array using shape method

In [13]:
array.dtype

dtype('int32')

Find type of the data of the array using dtype method

In [21]:
np.zeros(6)

array([ 0.,  0.,  0.,  0.,  0.,  0.])

Create array of size 6 of zeros using zeros method 

In [22]:
np.zeros((5,5))

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]])

Create two dimensional array of zeros of size 5*5 using zeros

In [23]:
np.ones((4,4))

array([[ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.]])

Create two dimensional array of ones of size 4*4 using ones method 

In [25]:
np.empty((2,2))

array([[              nan,   4.94065646e-324],
       [  4.64421707e-321,   4.94065646e-324]])

Create empty array of size 2*2 (two dimensional)

In [26]:
np.eye(4)

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.]])

Create two dimensional array of zeros and diameter of ones of size 4*4

In [27]:
np.arange(6)

array([0, 1, 2, 3, 4, 5])

Using a range to create array of size 6