# Indexing Arrays

In [1]:
import numpy as np

In [2]:
array1 = np.arange(0,11)

Create array of integers of size 10 

In [3]:
array1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

print out the array

In [4]:
array1[8]

8

Get element from the array by its index

In [5]:
array1[0:4]

array([0, 1, 2, 3])

Get elements in a range from the beginning until the fourth element 

In [4]:
array1[0:4]=100

changing the value of the four five elements

In [6]:
array1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

print out the array 

In [7]:
array1 = np.arange(0,11)
array1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

Reset array1 

In [8]:
slice_of_arr = array1[0:6]
slice_of_arr

array([0, 1, 2, 3, 4, 5])

Slices the array 

In [9]:
slice_of_arr[:]=44
slice_of_arr

array([44, 44, 44, 44, 44, 44])

Change the value of the Slices

In [10]:
array1

array([44, 44, 44, 44, 44, 44,  6,  7,  8,  9, 10])

In [14]:
arr_copy = array1.copy()
arr_copy

array([44, 44, 44, 44, 44, 44,  6,  7,  8,  9, 10])

Get a copy of the array 

In [15]:
arr_2d = np.array(([5,10,15],[20,25,30],[35,40,45]))
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

Indexing a two dimensional array 

In [16]:
arr_2d[1]

array([20, 25, 30])

get element from the two dimensional array by its index

In [17]:
arr_2d[1][0]

20

Get individual element value by its index

In [18]:
arr_2d[1,0]

20

Another way to get individual element value by its index

In [19]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

get subset of the array

In [20]:
arr_2d[2]

array([35, 40, 45])

Shape bottom row

In [21]:
arr_2d[2,:]

array([35, 40, 45])

Shape bottom row

In [22]:
arr2d = np.zeros((10,10))

In [23]:
arr_length = arr2d.shape[1]

get Length of array

In [24]:
for i in range(arr_length):
    arr2d[i] = i
    
arr2d

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.],
       [ 3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.],
       [ 4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.],
       [ 5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.],
       [ 6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.],
       [ 7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.],
       [ 8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.],
       [ 9.,  9.,  9.,  9.,  9.,  9.,  9.,  9.,  9.,  9.]])

Set up array

In [25]:
arr2d[[2,4,6,8]]

array([[ 2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.],
       [ 4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.],
       [ 6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.],
       [ 8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.]])

In [26]:
arr2d[[6,4,2,7]]

array([[ 6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.],
       [ 4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.],
       [ 2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.],
       [ 7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.]])

Allows in any order in the array 