# Using arrays and scalars

In [2]:
import numpy as np

importing numpy library

In [3]:
from __future__ import division

In [4]:
array1 = np.array([[1,2,3],[8,9,10]])

Create a new two dimensional array of integers array1

In [5]:
array1

array([[ 1,  2,  3],
       [ 8,  9, 10]])

print out the array1

In [6]:
array1*array1

array([[  1,   4,   9],
       [ 64,  81, 100]])

Multiply two arrays of integers

In [7]:
array1-array1

array([[0, 0, 0],
       [0, 0, 0]])

Subtract array1 from array1

In [8]:
1/array1

array([[ 1.        ,  0.5       ,  0.33333333],
       [ 0.125     ,  0.11111111,  0.1       ]])

In [9]:
array1**1

array([[ 1,  2,  3],
       [ 8,  9, 10]], dtype=int32)

Exponential (1)

In [10]:
array1**2

array([[  1,   4,   9],
       [ 64,  81, 100]], dtype=int32)

Exponential (2)